### ISSUE TITLE
Resolver endstops

### ISSUE THREAD

**Issue by alejandrocragnolini** [diegognavarro/S-Box-Core-XY#6]
El endstop de Z no es muy repetible, la varilla M5 es muy larga y cuesta ajustarla con precisión.
El del Y está bien ubicado, diseñamos una pieza que va justo, aunque sería positivo hacer mejores ajustes.
El del X también lo metimos en una pieza, pero quedó media complicada.

Propongo:
- Rehacer el mecanismo del Z, dejar un lugar en el carro para un sensor inductivo
- Implementar mecanismo de ajuste para el endstop de Y, junto con la pieza impresa.
- Meter el endstop de X en el carro, con algo ajustable para evitar otra pieza impresa.

**Comment by diegognavarro** [comment]
Conicido con lo del Z, en mi caso lo resolví con una contratuerca, pero sería mejor usar algo mejor. 
El endstop del eje X, el carro tentativo tiene orificios para montar un endstop mecánico en el carro del lado derecho (por eso no agregué rodamiento de ese lado asi no molesta y con 3 estaría bien creo), el tope lo estaría haciendo contra el carro Y? del lado derecho (en mi caso use una pieza impresa de tope) 
Voy a chusmear como lo resolvieron ustedes para ver si entre como lo resolví en la version mia y la de ustedes se nos ocurre una mejor forma de resolverlo (principalmente lo que mencionas que sea regulable) en mi caso lo regulo imprimiendo otra pieza... :)

**Comment by diegognavarro** [comment]
Quedo modificado con un montaje regulable según el alto del hotend en la parte posterior y un orificio para roscar un tornillo (corto para evitar problemas) M5. Igual calculo que es mejor poner por debajo también una segunda tuerca una vez calibrado para evitar que a la larga se afloje.
